# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QuickJobs4u' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for QuickJobs4u

  target 'QuickJobs4u-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    # pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'

  end

  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  # Pods for QuickJobs4u
  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'
  #pod 'RNFirebase', :path => '../node_modules/react-native-firebase'
  # See http://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies
  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]
  pod 'DoubleConversion'
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"
  pod 'GoogleAppMeasurement'
end

